### ISSUE TITLE
Что будет, если у пользователя 10000 история и он купил ещё на 20000, по какой ставке будет рассчитываться?

### ISSUE THREAD

**Issue by coursar** [Lagunov-PRO/HW03_Bonus#2]

**Comment by Lagunov-PRO** [comment]
@coursar по ставке синей карты, т.к. принимается в расчёт только сумма на момент оплаты.

**Comment by Lagunov-PRO** [comment]
Нужно ли переделать и учитывать текущую покупку при расчёте бонусов?

**Comment by coursar** [comment]
нужно свериться с тем, что по этому поводу говорит спортмастер ))

**Comment by Lagunov-PRO** [comment]
@coursar ничего про это не нашёл, поэтому сделал вторую функцию для этого случая, заодно упростил условия проверки и убрал дублирующиеся return.

https://github.com/Lagunov-PRO/HW03_Bonus/blob/8ede17c4e970477e8091de27b2e0e2fa484fd52c/app/lib.py#L60-L71

**Comment by Lagunov-PRO** [comment]
@coursar Закрывать?
